steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: 
    [
      "build", 
      "-t", 
      "us-central1-docker.pkg.dev/uptok-ee6a3/test/my-node-app:latest",
      ".",
    ]

# Step 2: Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/artifact-registry/docker'
  args: ['push', 'us-central1-docker.pkg.dev/uptok-ee6a3/test/my-node-app:latest']

# Step 3: Deploy the updated image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'my-node-app' # Replace with your Cloud Run service name
    - '--image=us-central1-docker.pkg.dev/uptok-ee6a3/test/my-node-app:latest'

options:
  env:
    - 'LOGGING_OPTION=CLOUD_LOGGING_ONLY'
images:
- 'us-central1-docker.pkg.dev/uptok-ee6a3/test/my-node-app:latest'
logsBucket: heruko-backups
